name: ft_transcendence
services:
  database:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    secrets:
      - postgres_user_pw
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s

  go-server:
    build:
      context: ./go-server
      target: ${BACKEND_TARGET:-production}
    volumes:
      - ./go-server:/app
    secrets:
      - postgres_user_pw
      - jwt_private_key
      - jwt_public_key
      - internal_api_key
    env_file:
      - .env
    environment:
      - PORT=${BACKEND_PORT}
    networks:
      - db_network
      - backend_network
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api/health || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s

  go-pprof-proxy:
    image: alpine/socat
    container_name: go-pprof-proxy
    profiles:
      - testing
    ports:
      - "8080:8080"
    command: tcp-listen:8080,fork,reuseaddr tcp:go-server:8080
    depends_on:
      - go-server
    networks:
      - backend_network

  caddy-test:
    image: caddy:2-alpine
    restart: unless-stopped
    profiles:
      - testing
    ports:
      - "8000:80"
      - "8443:8443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend_network

secrets:
  postgres_user_pw:
    file: ../secrets/postgres_user_pw.txt
  jwt_private_key:
    file: ../secrets/jwt_private.pem
  jwt_public_key:
    file: ../secrets/jwt_public.pem
  internal_api_key:
    file: ../secrets/gameserver_api_key.txt

networks:
  db_network:
    name: db_network
    driver: bridge
  backend_network:
    name: backend_network
    driver: bridge

volumes:
  db_data:
  caddy_data:
  caddy_config:
